baseURL = "//ttrpg.twilighteve.com/"
theme = "hugo_theme_adam_eve"
DefaultContentLanguage = "en"

#Render Raw HTML
[markup.goldmark.renderer]
unsafe= true

# Enable GitInfo
enableGitInfo = true

# Enable Emoji, regarding https://www.webfx.com/tools/emoji-cheat-sheet
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[Languages]
[Languages.en]
languageCode = "en"
title = "About TTRPG"

[Languages.en.params]
description = "Table-Top Role-Playing Games and Table-Top Role-Playing Games Accessories"

# Use Git Commit Date as last edited date
EnableGitInfo = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
